#!/usr/bin/env bash
set -u

ROOT="${SCHAGLK_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
OUT="$ROOT/projects/generated"

usage() {
    echo "Usage: project-factory.sh <type> <name>"
    echo "Types:"
    echo "  web"
    echo "  api"
    echo "  python"
    echo "  android"
    echo "  game2d"
    echo "  game3d"
    echo "  pc"
    echo "  native"
}

safe_name() {
    echo "$1" | tr ' /' '__' | tr -cd '[:alnum:]_.-'
}

create_web() {
    mkdir -p "$1"
    cat > "$1/index.html" <<'HTML'
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>SCHAGLK Web Project</title>
<style>
body{font-family:sans-serif;margin:2rem;background:#121a24;color:#e8eff7}
button{padding:12px 18px}
</style>
</head>
<body>
<h1>SCHAGLK WEB</h1>
<p id="status">LIVE READY</p>
<button onclick="document.getElementById('status').textContent='INTERACTIVE TEST OK'">
TEST
</button>
<script src="app.js"></script>
</body>
</html>
HTML
    cat > "$1/app.js" <<'JS'
console.log("SCHAGLK WEB PROJECT READY");
JS
    cat > "$1/README.md" <<'MD'
# SCHAGLK Web Project

Generated by SCHAGLK Project Factory.
MD
}

create_api() {
    mkdir -p "$1"
    cat > "$1/server.py" <<'PY'
from http.server import BaseHTTPRequestHandler, HTTPServer
import json

class Handler(BaseHTTPRequestHandler):
    def send_json(self, data):
        body=json.dumps(data).encode()
        self.send_response(200)
        self.send_header("Content-Type","application/json")
        self.send_header("Content-Length",str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        self.send_json({
            "app":"SCHAGLK API",
            "status":"ok",
            "route":self.path
        })

HTTPServer(("127.0.0.1", 8765), Handler).serve_forever()
PY
    cat > "$1/README.md" <<'MD'
# SCHAGLK API

Minimal local HTTP API generated by SCHAGLK.
MD
}

create_python() {
    mkdir -p "$1"
    cat > "$1/main.py" <<'PY'
def main():
    print("SCHAGLK PYTHON PROJECT READY")

if __name__ == "__main__":
    main()
PY
    cat > "$1/requirements.txt" <<'REQ'
# SCHAGLK project dependencies
REQ
}

create_android() {
    mkdir -p "$1/app/src/main/java/com/schaglk/generated"
    mkdir -p "$1/app/src/main/res/values"

    cat > "$1/settings.gradle" <<'GRADLE'
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name="GeneratedAndroid"
include(":app")
GRADLE

    cat > "$1/build.gradle" <<'GRADLE'
plugins {
    id 'com.android.application' version '8.13.0' apply false
}
GRADLE

    cat > "$1/gradle.properties" <<'PROP'
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
PROP

    cat > "$1/app/build.gradle" <<'GRADLE'
plugins {
    id 'com.android.application'
}

android {
    namespace 'com.schaglk.generated'
    compileSdk 34

    defaultConfig {
        applicationId 'com.schaglk.generated'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
}
GRADLE

    cat > "$1/app/src/main/res/values/strings.xml" <<'XML'
<resources>
    <string name="app_name">SCHAGLK Generated</string>
</resources>
XML

    cat > "$1/app/src/main/res/values/styles.xml" <<'XML'
<resources>
    <style name="AppTheme" parent="@android:style/Theme.Material.NoActionBar"/>
</resources>
XML

    cat > "$1/app/src/main/AndroidManifest.xml" <<'XML'
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:theme="@style/AppTheme"
        android:label="@string/app_name">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
XML

    cat > "$1/app/src/main/java/com/schaglk/generated/MainActivity.java" <<'JAVA'
package com.schaglk.generated;

import android.app.Activity;
import android.os.Bundle;
import android.widget.TextView;

public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle state) {
        super.onCreate(state);
        TextView view = new TextView(this);
        view.setText("SCHAGLK ANDROID PROJECT READY");
        view.setTextSize(20);
        setContentView(view);
    }
}
JAVA

    cat > "$1/README.md" <<'MD'
# SCHAGLK Android Project

Android project generated by SCHAGLK.

Compilation is intentionally not performed by this generator.
MD
}

create_game2d() {
    mkdir -p "$1/src" "$1/assets"
    cat > "$1/src/main.js" <<'JS'
const game={
    type:"2D",
    status:"ready",
    width:800,
    height:450
};
console.log("SCHAGLK GAME 2D READY",game);
JS
    cat > "$1/game.json" <<'JSON'
{
  "engine":"SCHAGLK",
  "type":"2D",
  "status":"prototype-ready",
  "assets":"assets",
  "source":"src"
}
JSON
}

create_game3d() {
    mkdir -p "$1/src" "$1/assets"
    cat > "$1/src/main.js" <<'JS'
const scene={
    type:"3D",
    status:"ready",
    camera:true,
    lighting:true
};
console.log("SCHAGLK GAME 3D SCENE READY",scene);
JS
    cat > "$1/game.json" <<'JSON'
{
  "engine":"SCHAGLK",
  "type":"3D",
  "status":"prototype-ready",
  "assets":"assets",
  "source":"src"
}
JSON
}

create_pc() {
    mkdir -p "$1/src"
    cat > "$1/CMakeLists.txt" <<'CMAKE'
cmake_minimum_required(VERSION 3.10)
project(schaglk_pc)
set(CMAKE_CXX_STANDARD 17)
add_executable(schaglk_pc src/main.cpp)
CMAKE

    cat > "$1/src/main.cpp" <<'CPP'
#include <iostream>
int main() {
    std::cout << "SCHAGLK PC PROJECT READY" << std::endl;
    return 0;
}
CPP
}

create_native() {
    mkdir -p "$1/src"
    cat > "$1/src/main.c" <<'C'
#include <stdio.h>
int main(void) {
    puts("SCHAGLK NATIVE PROJECT READY");
    return 0;
}
C
}

TYPE="${1:-}"
NAME="${2:-}"

[ -n "$TYPE" ] || { usage; exit 1; }
[ -n "$NAME" ] || { usage; exit 1; }

NAME="$(safe_name "$NAME")"
TARGET="$OUT/$NAME"

rm -rf "$TARGET"
mkdir -p "$TARGET"

case "$TYPE" in
    web) create_web "$TARGET" ;;
    api) create_api "$TARGET" ;;
    python) create_python "$TARGET" ;;
    android) create_android "$TARGET" ;;
    game2d) create_game2d "$TARGET" ;;
    game3d) create_game3d "$TARGET" ;;
    pc) create_pc "$TARGET" ;;
    native) create_native "$TARGET" ;;
    *) usage; exit 1 ;;
esac

cat > "$TARGET/schaglk-project.json" <<JSON
{
  "name":"$NAME",
  "type":"$TYPE",
  "generatedBy":"SCHAGLK",
  "status":"generated"
}
JSON

echo "PROJECT_CREATED=$TARGET"
